check which fail, should also check they fail correctly right now

diff --git a/.github/workflows/tester.yml b/.github/workflows/tester.yml
--- a/.github/workflows/tester.yml
+++ b/.github/workflows/tester.yml
@@ -69,7 +69,7 @@ jobs:
         minimum-pass: "0.7"
         assert-check: "false"
         max-fails: "2"  
-  v3-mono:
+  v3-mono-70percentfail:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
@@ -81,9 +81,17 @@ jobs:
         path: "tester_GUT_v7.4.1"
         import-time: "5"
         test-timeout: "45"
-        minimum-pass: "0.6"
+        minimum-pass: "0.7"
         test-dir: "res://test"
         config-file: "res://.gutconf.json"
+    - id: bad_success
+      if: ${{ always() && success() }}
+      run: echo "bad_success=1" >> $GITHUB_OUTPUT
+    - name: fail if test succeeded
+      if: ${{ always() && steps.bad_success.outputs.bad_success == 1 }}
+      run: |
+        echo "test did not fail, job failed"
+        exit 1
   v3-2:
     runs-on: ubuntu-latest
     steps:
@@ -97,21 +105,12 @@ jobs:
         test-timeout: "2"
         minimum-pass: "0.7"
         import-time: "3"
-    - id: bad_success
-      if: ${{ always() && success() }}
-      run: echo "bad_success=1" >> $GITHUB_OUTPUT
-    - name: fail on success
-      if: ${{ always() && steps.bad_success.outputs.bad_success == 1 }}
-      run: |
-        echo "test did not fail, job failed"
-        exit 1
   v3-fail-80percent:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - run: npm ci && npm run build
     - uses: ./
-      continue-on-error: true
       with:
         version: "3.2.2"
         path: "tester_GUT_v7.4.1"
@@ -124,7 +123,6 @@ jobs:
     - uses: actions/checkout@v2
     - run: npm ci && npm run build
     - uses: ./
-      continue-on-error: true
       with:
         version: "3.2.2"
         path: "tester_GUT_v7.4.1"
@@ -135,7 +133,6 @@ jobs:
     - uses: actions/checkout@v2
     - run: npm ci && npm run build
     - uses: ./
-      continue-on-error: true
       with:
         version: "3.4"
         release_type: "rc2"
@@ -177,7 +174,6 @@ jobs:
     - uses: actions/checkout@v2
     - run: npm ci && npm run build
     - uses: ./
-      continue-on-error: true
       with:
         version: "3.2.2"
         path: "tester_GUT_v7.4.1"
