attempt method 2

diff --git a/.github/workflows/tester.yml b/.github/workflows/tester.yml
--- a/.github/workflows/tester.yml
+++ b/.github/workflows/tester.yml
@@ -99,10 +99,12 @@ jobs:
         import-time: "3"
     - id: bad_success
       if: ${{ always() && success() }}
-      run: echo ::set-output name=bad_success::1
+      run: echo "bad_success=1" >> $GITHUB_OUTPUT
     - name: fail on success
-      if: ${{ always() && job.v3-2.steps.bad_success.outputs.bad_success == 1 }}
-      run: echo "test did not fail, job failed" && exit 1
+      if: ${{ always() && env.bad_success == 1 }}
+      run: |
+        echo "test did not fail, job failed"
+        exit 1
   v3-fail-80percent:
     runs-on: ubuntu-latest
     steps:
